# filename: tests/test_02_dashboard_validations.py | Code Generated by Sidekick is for learning and experimentation purposes only.

import os
from pathlib import Path

import pytest
from playwright.async_api import Page

from pages.dashboard_page import DashboardPage
from pages.login_page import LoginPage


@pytest.mark.asyncio
async def test_dashboard_validations(page: Page):
    username = os.getenv("LMS_USERNAME")
    password = os.getenv("LMS_PASSWORD")

    if not username or not password:
        raise AssertionError(
            "LMS_USERNAME and LMS_PASSWORD must be set "
            "in the current terminal."
        )

    login_page = LoginPage(page)

    await login_page.navigate()
    await login_page.login(username, password)
    await login_page.validate_successful_login()

    dashboard_page = DashboardPage(page)

    await dashboard_page.dismiss_cookie_dialog()
    await dashboard_page.validate_leave_summary()
    await dashboard_page.validate_profile_details(username)

    await page.keyboard.press("Escape")
    await dashboard_page.dismiss_cookie_dialog()

    await dashboard_page.validate_side_navigation()

    screenshot_directory = (
        Path(__file__).resolve().parents[1] / "screenshots"
    )

    screenshot_directory.mkdir(exist_ok=True)

    await page.screenshot(
        path=str(
            screenshot_directory
            / "task_02_dashboard_validations.png"
        ),
        full_page=True,
    )

    print("\nTask 2 dashboard validations completed successfully.")
