# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: tests/test_06_logout.py

import os

import pytest
from playwright.async_api import Page, TimeoutError

from pages.login_page import LoginPage
from pages.logout_page import LogoutPage


@pytest.mark.asyncio
async def test_logout(page: Page):
    username = os.getenv("LMS_USERNAME")
    password = os.getenv("LMS_PASSWORD")

    if not username or not password:
        raise AssertionError(
            "LMS_USERNAME and LMS_PASSWORD are not set."
        )

    login_page = LoginPage(page)
    await login_page.navigate()

    dashboard_marker = page.get_by_text(
        "Leave Summary",
        exact=True,
    )

    try:
        await dashboard_marker.wait_for(
            state="visible",
            timeout=5_000,
        )
        print("Existing login session detected.")
    except TimeoutError:
        await login_page.login(username, password)
        await login_page.validate_successful_login()

    # Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: tests/test_06_logout.py

    logout_page = LogoutPage(page)

    # Capture the profile dropdown before logout.
    await logout_page.capture_screenshot(
        "task_06_profile_menu_before_logout.png"
    )

    await logout_page.logout()
    await logout_page.validate_logged_out()

    # Capture the final logged-out state.
    await logout_page.capture_screenshot(
        "task_06_logged_out.png"
    )

    print("Logout completed and validated successfully.")

