# filename: tests/test_01_login.py | Code Generated by Sidekick is for learning and experimentation purposes only.
import os
from pathlib import Path

import pytest
from playwright.async_api import Page

from pages.login_page import LoginPage


@pytest.mark.asyncio
async def test_login(page: Page):
    username = os.getenv("LMS_USERNAME")
    password = os.getenv("LMS_PASSWORD")

    if not username or not password:
        raise AssertionError(
            "LMS_USERNAME and LMS_PASSWORD must be set "
            "in the current terminal."
        )

    login_page = LoginPage(page)

    await login_page.navigate()
    await login_page.login(username, password)
    await login_page.validate_successful_login()

    screenshot_directory = (
        Path(__file__).resolve().parents[1] / "screenshots"
    )

    screenshot_directory.mkdir(exist_ok=True)

    await page.screenshot(
        path=str(
            screenshot_directory / "task_01_login_success.png"
        ),
        full_page=True
    )

    print("Task 1 login completed successfully.")
