# filename: tests/test_03_apply_leave.py
# Code Generated by Sidekick is for learning and experimentation purposes only.

import os
from pathlib import Path

import pytest
from playwright.async_api import Page

from pages.apply_leave_page import ApplyLeavePage
from pages.login_page import LoginPage


@pytest.mark.asyncio
async def test_apply_leave(page: Page):
    username = os.getenv("LMS_USERNAME")
    password = os.getenv("LMS_PASSWORD")

    if not username or not password:
        raise AssertionError(
            "LMS_USERNAME and LMS_PASSWORD must be set "
            "in the current terminal."
        )

    login_page = LoginPage(page)

    await login_page.navigate()
    await login_page.login(username, password)
    await login_page.validate_successful_login()

    apply_leave_page = ApplyLeavePage(page)

    await apply_leave_page.open_apply_leave_form()
    await apply_leave_page.fill_leave_type()
    await apply_leave_page.fill_dates()
    await apply_leave_page.fill_reason()
    await apply_leave_page.submit_leave()
    await apply_leave_page.validate_leave_applied()

    screenshot_directory = (
        Path(__file__).resolve().parents[1] / "screenshots"
    )

    screenshot_directory.mkdir(exist_ok=True)

    await page.screenshot(
        path=str(
            screenshot_directory / "task_03_apply_leave_success.png"
        ),
        full_page=True,
    )

    print("Task 3 apply leave completed successfully.")
