# filename: tests/test_04_cancel_leave.py | Code Generated by Sidekick is for learning and experimentation purposes only.

import os

import pytest
from playwright.async_api import Page, TimeoutError

from pages.cancel_leave_page import CancelLeavePage
from pages.login_page import LoginPage


@pytest.mark.asyncio
async def test_cancel_leave(page: Page):
    username = os.getenv("LMS_USERNAME")
    password = os.getenv("LMS_PASSWORD")

    if not username or not password:
        raise AssertionError(
            "LMS_USERNAME and LMS_PASSWORD are not set."
        )

    login_page = LoginPage(page)
    await login_page.navigate()

    try:
        await page.get_by_text(
            "Leave Summary",
            exact=True,
        ).wait_for(
            state="visible",
            timeout=5_000,
        )
        print("Existing login session detected.")
    except TimeoutError:
        await login_page.login(username, password)
        await login_page.validate_successful_login()

    cancel_page = CancelLeavePage(page)

    await cancel_page.capture_screenshot(
        "task_04_before_cancel.png"
    )

    await cancel_page.cancel_leave()

    await cancel_page.capture_screenshot(
        "task_04_after_cancel.png"
    )

    print("Leave cancellation completed successfully.")
