# filename: pages/cancel_leave_page.py | Code Generated by Sidekick is for learning and experimentation purposes only.

import re
from pathlib import Path

from playwright.async_api import Page


class CancelLeavePage:
    def __init__(self, page: Page):
        self.page = page

    async def _first_visible(self, locator):
        for index in range(await locator.count()):
            item = locator.nth(index)
            try:
                if await item.is_visible():
                    return item
            except Exception:
                continue
        return None

    async def dismiss_cookie_dialog(self):
        selectors = [
            "#onetrust-banner-sdk #onetrust-accept-btn-handler",
            "#onetrust-banner-sdk #onetrust-reject-all-handler",
            "#onetrust-banner-sdk #onetrust-close-btn-container button",
            "#onetrust-pc-sdk #close-pc-btn",
            "#onetrust-pc-sdk button[aria-label='Close']",
        ]

        for selector in selectors:
            button = await self._first_visible(
                self.page.locator(selector)
            )

            if button is None:
                continue

            try:
                await button.click(force=True, timeout=5_000)
                await self.page.wait_for_timeout(800)
                return
            except Exception:
                continue

        cookie_buttons = self.page.locator(
            "#onetrust-banner-sdk button, "
            "#onetrust-pc-sdk button"
        )

        for index in range(await cookie_buttons.count()):
            button = cookie_buttons.nth(index)

            try:
                if not await button.is_visible():
                    continue

                text = " ".join([
                    await button.inner_text(),
                    await button.get_attribute("aria-label") or "",
                ])

                if re.search(
                    r"accept\s*all|reject\s*all|close",
                    text,
                    re.IGNORECASE,
                ):
                    await button.click(force=True, timeout=5_000)
                    await self.page.wait_for_timeout(800)
                    return
            except Exception:
                continue

        await self.page.keyboard.press("Escape")

    # Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: pages/cancel_leave_page.py

    async def _find_tracker_item(self):
        tracker_pattern = re.compile(
            r"^\s*Leave\s*(?:&|and)\s*Absence\s+Tracker\s*$",
            re.IGNORECASE,
        )

        labels = self.page.get_by_text(tracker_pattern)

        for index in range(await labels.count()):
            label = labels.nth(index)

            try:
                if not await label.is_visible():
                    continue

                clickable = label.locator(
                    "xpath=ancestor-or-self::*["
                    "self::a or self::button or self::li or "
                    "@role='link' or @role='button' or "
                    "@tabindex='0'"
                    "][1]"
                )

                if await clickable.count():
                    return clickable.first

                return label
            except Exception:
                continue

        # Fallback for labels split across nested elements.
        elements = self.page.locator(
            "a:visible, button:visible, li:visible, "
            "div:visible, span:visible, "
            "[role='link']:visible, [role='button']:visible"
        )

        for index in range(await elements.count()):
            element = elements.nth(index)

            try:
                text = re.sub(
                    r"\s+",
                    " ",
                    await element.inner_text(),
                ).strip()

                if tracker_pattern.fullmatch(text):
                    return element
            except Exception:
                continue

        return None

    async def open_tracker(self):
        await self.dismiss_cookie_dialog()
        await self.page.wait_for_timeout(1_000)

        # Close only an open overlay; do not expand/collapse the sidebar.
        await self.page.keyboard.press("Escape")
        await self.page.wait_for_timeout(500)

        tracker_item = await self._find_tracker_item()

        if tracker_item is None:
            # The sidebar may be collapsed. Use only exact toggle names.
            toggle = self.page.get_by_role(
                "button",
                name=re.compile(
                    r"^\s*(expand|expand sidebar|"
                    r"open navigation|show navigation)\s*$",
                    re.IGNORECASE,
                ),
            )

            for index in range(await toggle.count()):
                candidate = toggle.nth(index)

                try:
                    if await candidate.is_visible():
                        await candidate.click(
                            force=True,
                            timeout=5_000,
                        )
                        await self.page.wait_for_timeout(1_000)
                        break
                except Exception:
                    continue

            tracker_item = await self._find_tracker_item()

        if tracker_item is None:
            body_text = await self.page.locator(
                "body"
            ).inner_text()

            raise AssertionError(
                "Leave & Absence Tracker navigation item was not found. "
                f"Current URL: {self.page.url}. "
                f"Visible page text: {body_text[:1500]}"
            )

        await tracker_item.scroll_into_view_if_needed()
        await tracker_item.click(
            force=True,
            timeout=10_000,
        )

        # Confirm that navigation actually completed.
        for _ in range(30):
            current_url = self.page.url.lower()
            page_text = await self.page.locator(
                "body"
            ).inner_text()

            if (
                "absence" in current_url
                or "leave-tracker" in current_url
                or re.search(
                    r"My\s+Scheduled\s+Absences",
                    page_text,
                    re.IGNORECASE,
                )
            ):
                return

            await self.page.wait_for_timeout(500)

        raise AssertionError(
            "Leave & Absence Tracker was clicked, "
            "but the tracker page did not load. "
            f"Current URL: {self.page.url}"
        )


    async def click_filter(self):
        selectors = [
            "button[aria-label*='filter' i]",
            "[role='button'][aria-label*='filter' i]",
            "button[title*='filter' i]",
            "[role='button'][title*='filter' i]",
        ]

        for selector in selectors:
            button = await self._first_visible(
                self.page.locator(selector)
            )

            if button is not None:
                await button.click(force=True, timeout=10_000)
                await self.page.wait_for_timeout(700)
                return

        buttons = self.page.locator(
            "button:visible, [role='button']:visible"
        )

        for index in range(await buttons.count()):
            button = buttons.nth(index)

            label = " ".join([
                await button.inner_text(),
                await button.get_attribute("aria-label") or "",
                await button.get_attribute("title") or "",
            ])

            if re.search(r"filter", label, re.IGNORECASE):
                await button.click(force=True, timeout=10_000)
                await self.page.wait_for_timeout(700)
                return

        raise AssertionError(
            "Filter icon was not found on Leave & Absence Tracker."
        )

    async def apply_leaves_filter(self):
        leaves = self.page.get_by_text("Leaves", exact=True)
        option = await self._first_visible(leaves)

        if option is None:
            raise AssertionError(
                "Leaves filter option was not found."
            )

        await option.click(force=True, timeout=10_000)
        await self.page.wait_for_timeout(500)

        apply_buttons = [
            self.page.get_by_role(
                "button",
                name=re.compile(r"^\s*Apply\s*$", re.IGNORECASE),
            ),
            self.page.get_by_text("Apply", exact=True),
        ]

        for locator in apply_buttons:
            button = await self._first_visible(locator)

            if button is not None:
                await button.click(force=True, timeout=10_000)
                break

        await self.page.wait_for_timeout(1_500)

    async def cancel_scheduled_leave(self):
        heading = self.page.get_by_text(
            re.compile(
                r"My\s+scheduled\s+absences",
                re.IGNORECASE,
            )
        )

        if await self._first_visible(heading) is None:
            raise AssertionError(
                "My Scheduled Absences section was not found."
            )

        cancel_locators = [
            self.page.get_by_role(
                "button",
                name=re.compile(r"^\s*Cancel\s*$", re.IGNORECASE),
            ),
            self.page.get_by_text("Cancel", exact=True),
        ]

        cancel_button = None

        for locator in cancel_locators:
            cancel_button = await self._first_visible(locator)

            if cancel_button is not None:
                break

        if cancel_button is None:
            raise AssertionError(
                "No cancellable leave was found in "
                "My Scheduled Absences."
            )

        await cancel_button.scroll_into_view_if_needed()
        await cancel_button.click(force=True, timeout=10_000)
        await self.page.wait_for_timeout(700)

        confirm_locators = [
            self.page.get_by_role(
                "button",
                name=re.compile(
                    r"confirm|yes|cancel\s+leave",
                    re.IGNORECASE,
                ),
            ),
            self.page.get_by_text(
                re.compile(
                    r"confirm|yes|cancel\s+leave",
                    re.IGNORECASE,
                )
            ),
        ]

        confirmation = None

        for locator in confirm_locators:
            confirmation = await self._first_visible(locator)

            if confirmation is not None:
                break

        if confirmation is not None:
            await confirmation.click(
                force=True,
                timeout=10_000,
            )

        await self.page.wait_for_timeout(1_500)

        success = self.page.get_by_text(
            re.compile(
                r"cancelled|canceled|successfully",
                re.IGNORECASE,
            )
        )

        if await self._first_visible(success) is None:
            print(
                "Cancellation submitted; no success message was detected."
            )

    async def capture_screenshot(self, filename):
        directory = (
            Path(__file__).resolve().parents[1]
            / "screenshots"
        )
        directory.mkdir(parents=True, exist_ok=True)

        path = directory / filename
        await self.page.screenshot(
            path=str(path),
            full_page=True,
        )
        print(f"Screenshot saved: {path}")

    async def cancel_leave(self):
        await self.open_tracker()
        await self.click_filter()
        await self.apply_leaves_filter()
        await self.cancel_scheduled_leave()
