# filename: pages/apply_leave_page.py
# Code Generated by Sidekick is for learning and experimentation purposes only.

import os
import re
from datetime import date, timedelta

from playwright.async_api import Page, TimeoutError as PlaywrightTimeoutError, expect


class ApplyLeavePage:
    def __init__(self, page: Page):
        self.page = page

    # filename: pages/apply_leave_page.py | Code Generated by Sidekick is for learning and experimentation purposes only.

    # filename: pages/apply_leave_page.py | Code Generated by Sidekick is for learning and experimentation purposes only.

    # filename: pages/apply_leave_page.py | Code Generated by Sidekick is for learning and experimentation purposes only.

    async def dismiss_cookie_dialog(self):
        for _ in range(20):
            clicked = await self.page.evaluate(
                """() => {
                    const cookieText =
                        /here.?s how we use cookies|how we use cookies/i;

                    const buttons = [
                        ...document.querySelectorAll(
                            "button, [role='button']"
                        )
                    ];

                    const isCookieClose = (element) => {
                        const label = (
                            element.innerText ||
                            element.textContent ||
                            element.getAttribute("aria-label") ||
                            ""
                        ).trim().toLowerCase();

                        if (label !== "close") {
                            return false;
                        }

                        let parent = element;

                        for (let i = 0; i < 10 && parent; i += 1) {
                            if (cookieText.test(parent.innerText || "")) {
                                return true;
                            }

                            parent = parent.parentElement;
                        }

                        return false;
                    };

                    const closeButton = buttons.find(isCookieClose);

                    if (!closeButton) {
                        return false;
                    }

                    closeButton.click();
                    return true;
                }"""
            )

            if clicked:
                await self.page.wait_for_timeout(1_000)
                return

            await self.page.wait_for_timeout(250)

        # Fallback when the cookie panel is keyboard-dismissible.
        await self.page.keyboard.press("Escape")
        await self.page.wait_for_timeout(500)


    # filename: pages/apply_leave_page.py | Code Generated by Sidekick is for learning and experimentation purposes only.

    # filename: pages/apply_leave_page.py
# Code Generated by Sidekick is for learning and experimentation purposes only.

    # filename: pages/apply_leave_page.py | Code Generated by Sidekick is for learning and experimentation purposes only.

    async def open_apply_leave_form(self):
        await self.dismiss_cookie_dialog()

        # Close the profile menu if it is open.
        await self.page.keyboard.press("Escape")
        await self.page.wait_for_timeout(500)

        pattern = re.compile(
            r"^\s*apply\s*(for\s*)?leave\s*$",
            re.IGNORECASE,
        )

        candidates = [
            self.page.get_by_role("button", name=pattern),
            self.page.get_by_role("link", name=pattern),
            self.page.get_by_text(pattern),
        ]

        target = None

        for locator in candidates:
            for index in range(await locator.count()):
                candidate = locator.nth(index)

                if await candidate.is_visible():
                    target = candidate
                    break

            if target is not None:
                break

        if target is None:
            buttons = await self.page.locator("button").all_inner_texts()
            links = await self.page.locator("a").all_inner_texts()

            raise AssertionError(
                "Apply Leave control was not found. "
                f"URL: {self.page.url}; "
                f"Buttons: {buttons}; Links: {links}"
            )

        clickable_parent = target.locator(
            "xpath=ancestor-or-self::*"
            "[self::button or self::a or @role='button'][1]"
        )

        if await clickable_parent.count():
            target = clickable_parent

        await target.scroll_into_view_if_needed()
        await target.click(force=True)

        for _ in range(20):
            body_text = (
                await self.page.locator("body").inner_text()
            ).lower()

            if re.search(
                r"leave\s*type|start\s*date|from\s*date|reason",
                body_text,
            ):
                return

            await self.page.wait_for_timeout(500)

        raise AssertionError(
            "Apply Leave was clicked, but the form did not open. "
            f"Current URL: {self.page.url}"
        )




    async def _find_visible(self, locators):
        for locator in locators:
            for index in range(await locator.count()):
                candidate = locator.nth(index)

                if await candidate.is_visible():
                    return candidate

        return None

    # filename: pages/apply_leave_page.py | Code Generated by Sidekick is for learning and experimentation purposes only.

    async def fill_leave_type(self):
        leave_type = os.getenv("LMS_LEAVE_TYPE", "Casual")

        field_candidates = [
            self.page.get_by_role(
                "combobox",
                name=re.compile(
                    r"leave\s*type|type\s*of\s*leave",
                    re.IGNORECASE,
                ),
            ),
            self.page.get_by_label(
                re.compile(
                    r"leave\s*type|type\s*of\s*leave",
                    re.IGNORECASE,
                ),
            ),
            self.page.locator(
                "input[placeholder*='leave' i], "
                "input[name*='leave' i], "
                "[role='combobox']"
            ),
        ]

        leave_field = await self._find_visible(field_candidates)

        if leave_field is not None:
            tag_name = await leave_field.evaluate(
                "(element) => element.tagName.toLowerCase()"
            )

            if tag_name == "select":
                await leave_field.select_option(label=leave_type)
                return

            await leave_field.click(force=True)

        else:
            leave_type_text = self.page.get_by_text(
                re.compile(
                    r"leave\s*type|type\s*of\s*leave",
                    re.IGNORECASE,
                )
            ).first

            await expect(leave_type_text).to_be_visible(
                timeout=15_000
            )

            await leave_type_text.click(force=True)

        await self.page.wait_for_timeout(300)

        option = self.page.get_by_text(
            re.compile(
                rf"^{re.escape(leave_type)}$",
                re.IGNORECASE,
            )
        ).last

        await expect(option).to_be_visible(timeout=15_000)
        await option.click(force=True)


    # filename: pages/apply_leave_page.py
# Code Generated by Sidekick is for learning and experimentation purposes only.

    # filename: pages/apply_leave_page.py | Code Generated by Sidekick is for learning and experimentation purposes only.

    # filename: pages/apply_leave_page.py
# Code Generated by Sidekick is for learning and experimentation purposes only.

    async def _set_date_value(self, field, iso_value):
        await field.scroll_into_view_if_needed()

        input_type = (
            await field.get_attribute("type") or "text"
        ).lower()

        value_to_set = iso_value

        if input_type != "date":
            value_to_set = date.fromisoformat(
                iso_value
            ).strftime("%m/%d/%Y")

        try:
            await field.fill(
                value_to_set,
                timeout=5_000,
            )
        except Exception:
            await field.evaluate(
                """(element, value) => {
                    const setter =
                        Object.getOwnPropertyDescriptor(
                            HTMLInputElement.prototype,
                            "value"
                        ).set;

                    setter.call(element, value);

                    element.dispatchEvent(
                        new Event("input", { bubbles: true })
                    );

                    element.dispatchEvent(
                        new Event("change", { bubbles: true })
                    );

                    element.dispatchEvent(
                        new Event("blur", { bubbles: true })
                    );
                }""",
                value_to_set,
            )

    # filename: pages/apply_leave_page.py
# Code Generated by Sidekick is for learning and experimentation purposes only.

    async def fill_dates(self):
        start_date = os.getenv(
            "LMS_LEAVE_START_DATE",
            "2026-09-22",
        )

        end_date = os.getenv(
            "LMS_LEAVE_END_DATE",
            start_date,
        )

        # Use only fields belonging to the currently opened leave form.
        form = self.page.locator(
            "form:visible, "
            "[role='dialog']:visible, "
            "section:visible"
        ).last

        if await form.count() == 0:
            form = self.page.locator("body")

        # First preference: native date inputs.
        date_fields = form.locator(
            "input[type='date']:visible"
        )

        visible_date_fields = []

        for index in range(await date_fields.count()):
            field = date_fields.nth(index)

            if await field.is_visible():
                visible_date_fields.append(field)

        # Second preference: text inputs associated with date labels.
        if len(visible_date_fields) < 2:
            labelled_fields = form.locator(
                "input:visible"
            )

            for index in range(await labelled_fields.count()):
                field = labelled_fields.nth(index)

                field_type = (
                    await field.get_attribute("type") or ""
                ).lower()

                name = (
                    await field.get_attribute("name") or ""
                ).lower()

                field_id = (
                    await field.get_attribute("id") or ""
                ).lower()

                placeholder = (
                    await field.get_attribute("placeholder") or ""
                ).lower()

                descriptor = " ".join(
                    [name, field_id, placeholder]
                )

                if (
                    field_type != "hidden"
                    and (
                        "date" in descriptor
                        or "from" in descriptor
                        or "to" in descriptor
                        or "start" in descriptor
                        or "end" in descriptor
                    )
                ):
                    if field not in visible_date_fields:
                        visible_date_fields.append(field)

        if len(visible_date_fields) < 2:
            inputs = await form.locator(
                "input:visible"
            ).count()

            raise AssertionError(
                "Could not find two date fields in the open "
                f"Apply Leave form. Visible inputs found: {inputs}"
            )

        start_field = visible_date_fields[0]
        end_field = visible_date_fields[1]

        await self._enter_date_without_calendar(
            start_field,
            start_date,
        )

        await self._enter_date_without_calendar(
            end_field,
            end_date,
        )

        await self.page.wait_for_timeout(500)

    async def _enter_date_without_calendar(
        self,
        field,
        iso_value,
    ):
        await field.scroll_into_view_if_needed()

        field_type = (
            await field.get_attribute("type") or "text"
        ).lower()

        if field_type == "date":
            value = iso_value
        else:
            value = date.fromisoformat(
                iso_value
            ).strftime("%m/%d/%Y")

        # Prevent the native calendar popup from being opened.
        await field.focus()

        try:
            await field.fill(value, timeout=3_000)
        except Exception:
            await field.evaluate(
                """(element, value) => {
                    const setter =
                        Object.getOwnPropertyDescriptor(
                            HTMLInputElement.prototype,
                            "value"
                        ).set;

                    if (setter) {
                        setter.call(element, value);
                    } else {
                        element.value = value;
                    }

                    element.dispatchEvent(
                        new Event("input", { bubbles: true })
                    );

                    element.dispatchEvent(
                        new Event("change", { bubbles: true })
                    );

                    element.dispatchEvent(
                        new Event("blur", { bubbles: true })
                    );
                }""",
                value,
            )

        await field.press("Tab")





    async def fill_reason(self):
        reason = os.getenv(
            "LMS_LEAVE_REASON",
            "Personal leave requested for testing.",
        )

        reason_field = await self._find_visible(
            [
                self.page.get_by_label(
                    re.compile(
                        r"reason|remarks|comments",
                        re.IGNORECASE,
                    )
                ),
                self.page.locator("textarea").first,
            ]
        )

        if reason_field is not None:
            await reason_field.fill(reason)

    async def submit_leave(self):
        submit_button = await self._find_visible(
            [
                self.page.get_by_role(
                    "button",
                    name=re.compile(
                        r"submit|apply leave|request leave",
                        re.IGNORECASE,
                    ),
                ),
                self.page.locator(
                    "button[type='submit'], input[type='submit']"
                ),
            ]
        )

        if submit_button is None:
            raise AssertionError("Leave submit button was not found.")

        await submit_button.scroll_into_view_if_needed()
        await submit_button.click(force=True)

    async def validate_leave_applied(self):
        success_message = self.page.get_by_text(
            re.compile(
                r"leave.*(applied|submitted|success)"
                r"|successfully.*leave",
                re.IGNORECASE,
            )
        )

        try:
            await expect(success_message.first).to_be_visible(
                timeout=15_000
            )
            print("Leave was applied successfully.")
            return
        except PlaywrightTimeoutError:
            pass

        upcoming_leaves = self.page.get_by_role(
            "heading",
            name=re.compile(
                r"my upcoming leaves",
                re.IGNORECASE,
            ),
        )

        await expect(upcoming_leaves.first).to_be_visible(
            timeout=15_000
        )

        print("Leave was applied successfully.")
