# filename: conftest.py | Code Generated by Sidekick is for learning and experimentation purposes only.
import pytest_asyncio
from playwright.async_api import async_playwright


@pytest_asyncio.fixture
async def page():
    async with async_playwright() as playwright:
        browser = await playwright.chromium.launch(
            headless=False,
            slow_mo=700
        )

        context = await browser.new_context(
            viewport={"width": 1440, "height": 900}
        )

        page = await context.new_page()

        yield page

        await context.close()
        await browser.close()
