# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: tests/test_05_holiday_calendar.py

import os

import pytest
from playwright.async_api import Page

from pages.holiday_calendar_page import (
    HolidayCalendarPage,
)
from pages.login_page import LoginPage


@pytest.mark.asyncio
async def test_holiday_calendar(page: Page):
    username = os.getenv("LMS_USERNAME")
    password = os.getenv("LMS_PASSWORD")

    if not username or not password:
        raise AssertionError(
            "LMS_USERNAME and LMS_PASSWORD must be set."
        )

    login_page = LoginPage(page)

    await login_page.navigate()
    await login_page.login(username, password)
    await login_page.validate_successful_login()

    holiday_page = HolidayCalendarPage(page)

    await holiday_page.open_holiday_calendar()

    holidays = (
        await holiday_page.print_months_and_holidays()
    )

    assert holidays, (
        "Holiday Calendar contains no month data."
    )

    await holiday_page.capture_screenshot()

    print(
        "Task 5 Holiday Calendar completed successfully."
    )
