# filename: pages/dashboard_page.py | Code Generated by Sidekick is for learning and experimentation purposes only.

import os
import re

from playwright.async_api import (
    Page,
    TimeoutError as PlaywrightTimeoutError,
    expect,
)


class DashboardPage:
    CATEGORIES = ["Privileged", "Casual", "Encashed", "Taken"]

    SIDE_NAVIGATION = [
        "Collapse",
        "Dashboard",
        "Leave & Absence Tracker",
        "Holiday Calendar",
    ]

    def __init__(self, page: Page):
        self.page = page

    # filename: pages/dashboard_page.py | Code Generated by Sidekick is for learning and experimentation purposes only.

    # filename: pages/dashboard_page.py | Code Generated by Sidekick is for learning and experimentation purposes only.

    async def dismiss_cookie_dialog(self):
        dialog = self.page.get_by_role(
            "dialog",
            name=re.compile(
                r"how we use cookies",
                re.IGNORECASE,
            ),
        ).last

        if await dialog.count() == 0:
            return

        if not await dialog.is_visible():
            return

        close_button = dialog.get_by_role(
            "button",
            name=re.compile(r"^close$", re.IGNORECASE),
        ).last

        if await close_button.count() > 0:
            # Directly trigger the button because it may be below the viewport.
            await close_button.evaluate(
                "(element) => element.click()"
            )
        else:
            await self.page.keyboard.press("Escape")

        await expect(dialog).to_be_hidden(timeout=10_000)



    async def validate_leave_summary(self):
        heading = self.page.get_by_role(
            "heading",
            name=re.compile(r"^Leave Summary$", re.IGNORECASE),
        )

        if await heading.count():
            await expect(heading.first).to_be_visible(timeout=30_000)
        else:
            await expect(
                self.page.get_by_text("Leave Summary", exact=True)
            ).to_be_visible(timeout=30_000)

        print("\nLeave Summary categories:")

        for category in self.CATEGORIES:
            category_locator = self.page.get_by_text(
                category,
                exact=True,
            )

            await expect(
                category_locator.first
            ).to_be_visible(timeout=30_000)

            count_text = await self._find_leave_count(category_locator.first)

            if not count_text:
                raise AssertionError(
                    f"Leave count was not found for category: {category}"
                )

            print(f"{category}: {count_text}")

    async def _find_leave_count(self, category_locator):
        count_pattern = re.compile(
            r"\d+(?:\.\d+)?\s*(?:hrs?|d)"
            r"(?:\s*\|\s*\d+(?:\.\d+)?\s*d)?",
            re.IGNORECASE,
        )

        current_locator = category_locator
        last_text = ""

        for _ in range(6):
            last_text = " ".join(
                (await current_locator.inner_text()).split()
            )

            match = count_pattern.search(last_text)

            if match:
                return match.group(0)

            current_locator = current_locator.locator("xpath=..")

        return None

    async def validate_profile_details(self, username: str):
        await self._open_profile_menu()

        expected_email = os.getenv(
            "LMS_EXPECTED_EMAIL",
            f"{username}@deloitte.com",
        )

        expected_role = os.getenv(
            "LMS_EXPECTED_ROLE",
            "Quality Engineer-I",
        )

        expected_employee_id = os.getenv(
            "LMS_EXPECTED_EMP_ID",
            "5500967",
        )

        await expect(
            self.page.get_by_text(
                expected_email,
                exact=True,
            )
        ).to_be_visible(timeout=30_000)

        await expect(
            self.page.get_by_text(
                expected_role,
                exact=True,
            )
        ).to_be_visible(timeout=30_000)

        await expect(
            self.page.get_by_text(
                re.compile(
                    rf"Emp\s*Id\s*-\s*{re.escape(expected_employee_id)}",
                    re.IGNORECASE,
                )
            )
        ).to_be_visible(timeout=30_000)

        print("\nProfile validation passed:")
        print(f"Email: {expected_email}")
        print(f"Role: {expected_role}")
        print(f"Employee ID: {expected_employee_id}")

    # filename: pages/dashboard_page.py | Code Generated by Sidekick is for learning and experimentation purposes only.

    # filename: pages/dashboard_page.py | Code Generated by Sidekick is for learning and experimentation purposes only.

    async def _open_profile_menu(self):
        await self.dismiss_cookie_dialog()

        profile_name = self.page.locator(
            "span.user-profile-trigger-name"
        ).first

        await expect(profile_name).to_be_visible(
            timeout=30_000
        )

        await profile_name.scroll_into_view_if_needed()

        profile_trigger = profile_name.locator("xpath=..")

        await profile_trigger.click(
            force=True,
            timeout=10_000,
        )

        await self.page.wait_for_timeout(500)



    # Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: pages/dashboard_page.py

    async def validate_side_navigation(self):
        await self.dismiss_cookie_dialog()

        # Close the profile dropdown if it is still open.
        await self.page.keyboard.press("Escape")
        await self.page.wait_for_timeout(300)

        async def is_visible_text(text):
            locator = self.page.get_by_text(text, exact=True)

            for index in range(await locator.count()):
                if await locator.nth(index).is_visible():
                    return True

            return False

        # Expand the sidebar only when "Collapse" is not currently visible.
        if not await is_visible_text("Collapse"):
            menu_icon = self.page.locator(
                "img[alt='collapse menu icon']"
            )

            if not await menu_icon.count():
                menu_icon = self.page.get_by_role(
                    "img",
                    name=re.compile(
                        r"collapse menu icon",
                        re.IGNORECASE,
                    ),
                )

            if not await menu_icon.count():
                raise AssertionError(
                    "The sidebar menu icon was not found."
                )

            menu_icon = menu_icon.first

            await menu_icon.click(
                force=True,
                timeout=10_000,
            )

            for _ in range(20):
                if await is_visible_text("Collapse"):
                    break

                await self.page.wait_for_timeout(250)

        expected_options = [
            "Collapse",
            "Dashboard",
            "Leave & Absence Tracker",
            "Holiday Calendar",
        ]

        for option in expected_options:
            if not await is_visible_text(option):
                raise AssertionError(
                    f"Side navigation option was not found: {option}"
                )

        print("\nSide navigation validation passed:")

        for option in expected_options:
            print(f"- {option}")

