# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: pages/holiday_calendar_page.py

import re
from pathlib import Path

from playwright.async_api import Page


class HolidayCalendarPage:
    MONTHS = {
        "jan": "January",
        "feb": "February",
        "mar": "March",
        "apr": "April",
        "may": "May",
        "jun": "June",
        "jul": "July",
        "aug": "August",
        "sep": "September",
        "oct": "October",
        "nov": "November",
        "dec": "December",
    }

    def __init__(self, page: Page):
        self.page = page

    # filename: pages/holiday_calendar_page.py | Code Generated by Sidekick is for learning and experimentation purposes only.

    # filename: pages/holiday_calendar_page.py | Code Generated by Sidekick is for learning and experimentation purposes only.

    async def _cookie_visible(self):
        return await self.page.evaluate(
            """() => {
                const selectors = [
                    "#onetrust-pc-sdk",
                    "#onetrust-banner-sdk"
                ];

                return selectors.some((selector) => {
                    const element = document.querySelector(selector);

                    if (!element) {
                        return false;
                    }

                    const style = window.getComputedStyle(element);
                    const rect = element.getBoundingClientRect();

                    return (
                        style.display !== "none" &&
                        style.visibility !== "hidden" &&
                        rect.width > 0 &&
                        rect.height > 0
                    );
                });
            }"""
        )

    # Code Generated by Sidekick is for learning and experimentation purposes only. | filename: pages/holiday_calendar_page.py

    # filename: pages/holiday_calendar_page.py
# Code Generated by Sidekick is for learning and experimentation purposes only.

    async def dismiss_cookie_dialog(self):
        selectors = [
            "#onetrust-banner-sdk #onetrust-accept-btn-handler",
            "#onetrust-banner-sdk #onetrust-reject-all-handler",
            "#onetrust-banner-sdk #onetrust-close-btn-container button",
            "#onetrust-pc-sdk #close-pc-btn",
            "#onetrust-pc-sdk button[aria-label='Close']",
        ]

        for selector in selectors:
            buttons = self.page.locator(selector)

            for index in range(await buttons.count()):
                button = buttons.nth(index)

                try:
                    if await button.is_visible():
                        await button.scroll_into_view_if_needed()
                        await button.click(
                            force=True,
                            timeout=5_000,
                        )
                        await self.page.wait_for_timeout(700)
                        return
                except Exception:
                    continue

        cookie_roots = self.page.locator(
            "#onetrust-banner-sdk:visible, "
            "#onetrust-pc-sdk:visible"
        )

        for root_index in range(await cookie_roots.count()):
            root = cookie_roots.nth(root_index)
            buttons = root.locator("button")

            for button_index in range(await buttons.count()):
                button = buttons.nth(button_index)

                try:
                    if not await button.is_visible():
                        continue

                    text = (
                        await button.inner_text()
                    ).strip()

                    aria_label = (
                        await button.get_attribute("aria-label")
                        or ""
                    )

                    label = f"{text} {aria_label}"

                    if re.search(
                        r"accept\s*all|reject\s*all|close",
                        label,
                        re.IGNORECASE,
                    ):
                        await button.scroll_into_view_if_needed()
                        await button.click(
                            force=True,
                            timeout=5_000,
                        )
                        await self.page.wait_for_timeout(700)
                        return
                except Exception:
                    continue

        await self.page.keyboard.press("Escape")
        await self.page.wait_for_timeout(500)

    async def _click_holiday_target(self):
        direct_targets = self.page.locator(
            "a[href*='holiday' i], "
            "[role='link'][href*='holiday' i], "
            "[aria-label*='holiday calendar' i], "
            "[title*='holiday calendar' i], "
            "[data-testid*='holiday' i], "
            "nav a[href*='calendar' i], "
            "aside a[href*='calendar' i]"
        )

        for index in range(await direct_targets.count()):
            target = direct_targets.nth(index)

            try:
                if await target.is_visible():
                    await target.click(
                        force=True,
                        timeout=5_000,
                    )
                    return True
            except Exception:
                continue

        labels = self.page.locator(
            "xpath=//*[normalize-space()='Holiday Calendar']"
        )

        for index in range(await labels.count()):
            label = labels.nth(index)

            try:
                if not await label.is_visible():
                    continue

                clickable = label.locator(
                    "xpath=ancestor-or-self::*"
                    "[self::a or self::button or self::li "
                    "or @role='link' or @role='button'][1]"
                )

                if await clickable.count():
                    target = clickable.first
                else:
                    target = label

                await target.scroll_into_view_if_needed()
                await target.click(
                    force=True,
                    timeout=5_000,
                )
                return True
            except Exception:
                continue

        return False

    async def open_holiday_calendar(self):
        await self.dismiss_cookie_dialog()

        # Close the profile menu if it is open.
        await self.page.keyboard.press("Escape")
        await self.page.wait_for_timeout(500)

        # First try the calendar link/icon while the sidebar is collapsed.
        if await self._click_holiday_target():
            await self.page.wait_for_timeout(1_500)
            return

        # Expand only an actual sidebar/navigation control.
        expand_controls = [
            self.page.get_by_role(
                "button",
                name=re.compile(
                    r"^\s*(expand|expand sidebar|"
                    r"open navigation|show navigation)\s*$",
                    re.IGNORECASE,
                ),
            ),
            self.page.locator(
                "button[aria-label='Expand'], "
                "button[aria-label='Expand sidebar'], "
                "button[title='Expand'], "
                "button[title='Expand sidebar'], "
                "[data-testid*='sidebar-toggle' i]"
            ),
        ]

        for controls in expand_controls:
            for index in range(await controls.count()):
                control = controls.nth(index)

                try:
                    if await control.is_visible():
                        await control.click(
                            force=True,
                            timeout=5_000,
                        )
                        await self.page.wait_for_timeout(800)

                        if await self._click_holiday_target():
                            await self.page.wait_for_timeout(1_500)
                            return
                except Exception:
                    continue

        body_text = await self.page.locator("body").inner_text()

        raise AssertionError(
            "Holiday Calendar navigation item was not found. "
            f"Current URL: {self.page.url}. "
            f"Visible page text: {body_text[:1500]}"
        )







    def _canonical_month(self, value):
        key = value.strip().lower()[:3]
        return self.MONTHS.get(key)

    async def print_months_and_holidays(self):
        main = self.page.locator("main:visible").first

        if await main.count():
            page_text = await main.inner_text()
        else:
            page_text = await self.page.locator(
                "body"
            ).inner_text()

        lines = [
            re.sub(r"\s+", " ", line).strip()
            for line in page_text.splitlines()
            if line.strip()
        ]

        month_pattern = re.compile(
            r"^(January|February|March|April|May|June|July|"
            r"August|September|October|November|December|"
            r"Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)"
            r"(?:\s+\d{4})?"
            r"(?:\s+(?:holidays?|leaves?))?"
            r"(?:\s*[:\-]\s*(.*))?$",
            re.IGNORECASE,
        )

        holidays = {}
        current_month = None

        ignored_lines = {
            "dashboard",
            "holiday calendar",
            "holiday schedule",
            "view all",
            "location information unavailable",
        }

        for line in lines:
            if line.lower() in ignored_lines:
                continue

            match = month_pattern.match(line)

            if match:
                current_month = self._canonical_month(
                    match.group(1)
                )
                holidays.setdefault(current_month, [])

                trailing_text = (match.group(2) or "").strip()

                if trailing_text:
                    holidays[current_month].append(
                        trailing_text
                    )

                continue

            if current_month:
                if line not in holidays[current_month]:
                    holidays[current_month].append(line)

        print("\nHoliday Calendar:")

        for month, entries in holidays.items():
            clean_entries = [
                entry
                for entry in entries
                if entry.lower() not in ignored_lines
            ]

            if clean_entries:
                print(
                    f"{month}: "
                    f"{' | '.join(clean_entries)}"
                )
            else:
                print(f"{month}: No holidays listed")

        if not holidays:
            raise AssertionError(
                "No month names were found on the Holiday Calendar page. "
                f"Page text: {page_text[:1500]}"
            )

        return holidays

    async def capture_screenshot(self):
        screenshot_directory = (
            Path(__file__).resolve().parents[1]
            / "screenshots"
        )

        screenshot_directory.mkdir(exist_ok=True)

        await self.page.screenshot(
            path=str(
                screenshot_directory
                / "task_05_holiday_calendar.png"
            ),
            full_page=True,
        )
