# filename: pages/login_page.py | Code Generated by Sidekick is for learning and experimentation purposes only.
import os
import re

from playwright.async_api import Page, expect


class LoginPage:
    def __init__(self, page: Page):
        self.page = page
        self.application_url = os.getenv("LMS_URL", "")

    async def _visible_locator(self, locators):
        for locator in locators:
            for index in range(await locator.count()):
                candidate = locator.nth(index)
                if await candidate.is_visible():
                    return candidate
        return None

    async def _find_username_field(self):
        return await self._visible_locator(
            [
                self.page.get_by_label(
                    re.compile(r"username|user\s*id|email", re.IGNORECASE)
                ),
                self.page.get_by_placeholder(
                    re.compile(r"username|user\s*id|email", re.IGNORECASE)
                ),
                self.page.locator(
                    "input[type='email'], input[type='text'], "
                    "input[name*='user' i], input[name*='email' i]"
                ),
            ]
        )

    async def _find_password_field(self):
        return await self._visible_locator(
            [
                self.page.get_by_label(
                    re.compile(r"password", re.IGNORECASE)
                ),
                self.page.get_by_placeholder(
                    re.compile(r"password", re.IGNORECASE)
                ),
                self.page.locator("input[type='password']"),
            ]
        )

    async def navigate(self):
        if not self.application_url:
            raise AssertionError(
                "LMS_URL is not set. Set it in the same terminal before running pytest."
            )

        await self.page.goto(
            self.application_url,
            wait_until="domcontentloaded"
        )

    async def login(self, username: str, password: str):
        username_field = await self._find_username_field()

        # Your website shows Sign In instead of Login using SSO.
        if username_field is None:
            sign_in_button = await self._visible_locator(
                [
                    self.page.get_by_role(
                        "button",
                        name=re.compile(
                            r"^\s*sign\s*in\s*$",
                            re.IGNORECASE
                        )
                    ),
                    self.page.get_by_role(
                        "link",
                        name=re.compile(
                            r"^\s*sign\s*in\s*$",
                            re.IGNORECASE
                        )
                    ),
                ]
            )

            if sign_in_button is None:
                raise AssertionError(
                    "The initial Sign In button was not found."
                )

            await sign_in_button.click()
            await self.page.wait_for_timeout(500)

            username_field = await self._find_username_field()

        if username_field is None:
            raise AssertionError("Username field was not found.")

        await username_field.fill(username)

        password_field = await self._find_password_field()

        if password_field is None:
            raise AssertionError("Password field was not found.")

        await password_field.fill(password)

        submit_button = await self._visible_locator(
            [
                self.page.get_by_role(
                    "button",
                    name=re.compile(
                        r"^\s*sign\s*in\s*$|^\s*login\s*$",
                        re.IGNORECASE
                    )
                ),
                self.page.locator(
                    "input[type='submit'], button[type='submit']"
                ),
            ]
        )

        if submit_button is None:
            raise AssertionError(
                "The final Sign In button was not found."
            )

        await submit_button.click()

    async def validate_successful_login(self):
        await expect(self.page).to_have_url(
            re.compile(r"/leaves(?:/|$)", re.IGNORECASE),
            timeout=30_000
        )

        leave_heading = self.page.get_by_role(
            "heading",
            name=re.compile(
                r"leave\s+summary",
                re.IGNORECASE
            )
        )

        if await leave_heading.count():
            await expect(leave_heading.first).to_be_visible(
                timeout=30_000
            )
        else:
            await expect(
                self.page.get_by_text(
                    "Leave Summary",
                    exact=True
                )
            ).to_be_visible(timeout=30_000)
