# Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: pages/logout_page.py

import re
import time

from playwright.async_api import Page

from pages.holiday_calendar_page import HolidayCalendarPage
from pathlib import Path

class LogoutPage:
    def __init__(self, page: Page):
        self.page = page

    async def _first_visible(self, locator):
        for index in range(await locator.count()):
            candidate = locator.nth(index)

            try:
                if await candidate.is_visible():
                    return candidate
            except Exception:
                continue

        return None

    async def _cookie_notice_visible(self):
        cookie_root = self.page.locator(
            "#onetrust-banner-sdk, #onetrust-pc-sdk"
        )

        return (
            await self._first_visible(cookie_root)
        ) is not None

    async def _wait_for_cookie_to_close(
        self,
        timeout_ms=3_000,
    ):
        deadline = time.monotonic() + (
            timeout_ms / 1_000
        )

        while time.monotonic() < deadline:
            if not await self._cookie_notice_visible():
                return True

            await self.page.wait_for_timeout(250)

        return not await self._cookie_notice_visible()

    async def dismiss_cookie_popup(self):
        # Reuse the cookie-dismissal logic that worked in Task 5.
        try:
            holiday_page = HolidayCalendarPage(self.page)
            await holiday_page.dismiss_cookie_dialog()
        except Exception:
            pass

        if await self._wait_for_cookie_to_close():
            return

        cookie_actions = [
            "#onetrust-reject-all-handler",
            "#onetrust-accept-btn-handler",
            "#onetrust-banner-sdk "
            "#onetrust-close-btn-container button",
            "#onetrust-banner-sdk button[aria-label='Close']",
            "#onetrust-pc-sdk #close-pc-btn",
            "#onetrust-pc-sdk button[aria-label='Close']",
        ]

        for selector in cookie_actions:
            action = await self._first_visible(
                self.page.locator(selector)
            )

            if action is None:
                continue

            try:
                await action.scroll_into_view_if_needed()
                await action.click(
                    force=True,
                    timeout=5_000,
                )

                if await self._wait_for_cookie_to_close():
                    return
            except Exception:
                continue

        cookie_buttons = self.page.locator(
            "#onetrust-banner-sdk button, "
            "#onetrust-pc-sdk button"
        )

        for index in range(await cookie_buttons.count()):
            button = cookie_buttons.nth(index)

            try:
                if not await button.is_visible():
                    continue

                label = " ".join(
                    [
                        await button.inner_text(),
                        await button.get_attribute(
                            "aria-label"
                        ) or "",
                    ]
                ).strip()

                if not re.fullmatch(
                    r"Accept All(?: Cookies)?|Reject All|Close",
                    label,
                    re.IGNORECASE,
                ):
                    continue

                await button.scroll_into_view_if_needed()
                await button.click(
                    force=True,
                    timeout=5_000,
                )

                if await self._wait_for_cookie_to_close():
                    return
            except Exception:
                continue

        # Safe final attempt before profile-menu interaction begins.
        await self.page.keyboard.press("Escape")

        if await self._wait_for_cookie_to_close():
            return

        raise AssertionError(
            "Cookie Notice is still visible and blocking "
            "the Logout task."
        )

    async def _visible_logout_option(self):
        logout_pattern = re.compile(
            r"^\s*Logout\s*$",
            re.IGNORECASE,
        )

        locators = [
            self.page.get_by_role(
                "menuitem",
                name=logout_pattern,
            ),
            self.page.get_by_role(
                "button",
                name=logout_pattern,
            ),
            self.page.get_by_text(logout_pattern),
        ]

        for locator in locators:
            visible_option = await self._first_visible(locator)

            if visible_option is not None:
                return visible_option

        return None

    async def _wait_for_logout_option(
        self,
        timeout_ms=4_000,
    ):
        deadline = time.monotonic() + (
            timeout_ms / 1_000
        )

        while time.monotonic() < deadline:
            option = await self._visible_logout_option()

            if option is not None:
                return option

            await self.page.wait_for_timeout(250)

        return None

    async def _page_width(self):
        body_box = await self.page.locator(
            "body"
        ).bounding_box()

        if body_box:
            return body_box["width"]

        viewport = self.page.viewport_size

        if viewport:
            return viewport["width"]

        return 1_920

    async def _click_and_wait_for_logout(self, target):
        try:
            await target.scroll_into_view_if_needed()
            await target.click(
                force=True,
                timeout=5_000,
            )
        except Exception:
            box = await target.bounding_box()

            if not box:
                return None

            await self.page.mouse.click(
                box["x"] + (box["width"] / 2),
                box["y"] + (box["height"] / 2),
            )

        logout_option = await self._wait_for_logout_option()

        if logout_option is not None:
            return logout_option

        # Retry using an actual mouse click for non-button profile controls.
        box = await target.bounding_box()

        if not box:
            return None

        await self.page.mouse.click(
            box["x"] + (box["width"] / 2),
            box["y"] + (box["height"] / 2),
        )

        return await self._wait_for_logout_option()

    async def _open_profile_menu(self):
        # If the dropdown is already open, do not click it again.
        logout_option = await self._visible_logout_option()

        if logout_option is not None:
            return logout_option

        page_width = await self._page_width()

        # This matches the visible "hashedintest..." label
        # shown in the top-right profile control.
        user_labels = self.page.get_by_text(
            re.compile(r"hashedintest", re.IGNORECASE)
        )

        for index in range(await user_labels.count()):
            label = user_labels.nth(index)

            try:
                if not await label.is_visible():
                    continue

                box = await label.bounding_box()

                if not box:
                    continue

                if box["y"] > 250:
                    continue

                if box["x"] < page_width * 0.50:
                    continue

                logout_option = (
                    await self._click_and_wait_for_logout(
                        label
                    )
                )

                if logout_option is not None:
                    return logout_option
            except Exception:
                continue

        # Semantic fallback if the profile control has accessibility labels.
        profile_controls = self.page.locator(
            "[aria-label*='profile' i], "
            "[aria-label*='account' i], "
            "[title*='profile' i], "
            "[title*='account' i], "
            "[aria-haspopup='menu'], "
            "[aria-expanded]"
        )

        for index in range(await profile_controls.count()):
            control = profile_controls.nth(index)

            try:
                if not await control.is_visible():
                    continue

                box = await control.bounding_box()

                if not box:
                    continue

                if (
                    box["y"] > 250
                    or box["x"] < page_width * 0.65
                ):
                    continue

                logout_option = (
                    await self._click_and_wait_for_logout(
                        control
                    )
                )

                if logout_option is not None:
                    return logout_option
            except Exception:
                continue

        # Final fallback: the profile area is at the top-right,
        # as shown in your screenshots.
        click_x = max(
            40,
            page_width - min(180, page_width * 0.20),
        )

        await self.page.mouse.click(click_x, 150)

        return await self._wait_for_logout_option()

    async def logout(self):
        await self.dismiss_cookie_popup()

        # Do not press Escape here. It could close an open profile menu.
        logout_option = await self._visible_logout_option()

        if logout_option is None:
            logout_option = await self._open_profile_menu()

        if logout_option is None:
            raise AssertionError(
                "Profile menu did not open, so Logout could "
                "not be found."
            )

        try:
            await logout_option.scroll_into_view_if_needed()
            await logout_option.click(
                force=True,
                timeout=10_000,
            )
        except Exception:
            box = await logout_option.bounding_box()

            if not box:
                raise AssertionError(
                    "Logout option was visible but could not "
                    "be clicked."
                )

            await self.page.mouse.click(
                box["x"] + (box["width"] / 2),
                box["y"] + (box["height"] / 2),
            )

        await self.page.wait_for_timeout(1_000)

    async def validate_logged_out(self):
        login_markers = [
            self.page.get_by_text(
                re.compile(
                    r"login\s+using\s+sso",
                    re.IGNORECASE,
                )
            ),
            self.page.get_by_role(
                "button",
                name=re.compile(
                    r"login|sign\s*in",
                    re.IGNORECASE,
                ),
            ),
            self.page.locator(
                "input[type='email'], "
                "input[name*='user'], "
                "input[name*='email']"
            ),
        ]

        deadline = time.monotonic() + 25

        while time.monotonic() < deadline:
            for marker in login_markers:
                if await self._first_visible(marker):
                    return

            # A redirect away from the protected dashboard
            # is also a valid logout result.
            if "/leaves/dashboard" not in self.page.url.lower():
                return

            await self.page.wait_for_timeout(500)

        raise AssertionError(
            "Logout could not be validated. "
            f"Current URL: {self.page.url}"
        )
        
    # Code Generated by Sidekick is for learning and experimentation purposes only.
# filename: pages/logout_page.py

    async def capture_screenshot(self, filename):
        screenshot_directory = (
            Path(__file__).resolve().parents[1]
            / "screenshots"
        )

        screenshot_directory.mkdir(
            parents=True,
            exist_ok=True,
        )

        screenshot_path = screenshot_directory / filename

        await self.page.screenshot(
            path=str(screenshot_path),
            full_page=True,
        )

        print(
            f"Screenshot saved: {screenshot_path}"
        )

